# Generated by Django 2.2.4 on 2020-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0002_activities_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Api_document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=300)),
                ('api_url', models.CharField(max_length=200)),
            ],
        ),
    ]
