# Generated by Django 2.2.4 on 2020-02-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0003_api_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location_add',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=400)),
                ('logitude', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=50)),
                ('overview', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=200)),
                ('facility', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('thumbnail1', models.FileField(default='', upload_to='thumbnail1')),
                ('thumbnail2', models.FileField(default='', upload_to='thumbnail2')),
                ('thumbnail3', models.FileField(default='', upload_to='thumbnail3')),
                ('other1', models.FileField(default='', upload_to='other1')),
                ('other2', models.FileField(default='', upload_to='other2')),
                ('other3', models.FileField(default='', upload_to='other3')),
            ],
        ),
    ]
