# Generated by Django 2.2.4 on 2020-03-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0004_location_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='history',
            field=models.CharField(default='empty', max_length=2000),
        ),
        migrations.AddField(
            model_name='categories',
            name='history',
            field=models.CharField(default='empty', max_length=2000),
        ),
        migrations.AddField(
            model_name='facilities',
            name='history',
            field=models.CharField(default='empty', max_length=2000),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='location_add',
            name='activity',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='location_add',
            name='category',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='location_add',
            name='facility',
            field=models.CharField(max_length=2000),
        ),
    ]
