# Generated by Django 2.2.4 on 2020-03-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0005_auto_20200303_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usa_state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('api_url', models.CharField(max_length=300)),
            ],
        ),
    ]
