# Generated by Django 2.2.4 on 2020-04-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0007_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtual',
            name='image',
            field=models.FileField(default='', upload_to='virtual'),
        ),
    ]
