# Generated by Django 2.2.4 on 2020-06-29 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0008_auto_20200421_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='usa_state',
            name='img',
            field=models.FileField(default='none', upload_to='state_img'),
        ),
    ]
