# Generated by Django 2.2.4 on 2020-07-02 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emanjha_admin', '0009_usa_state_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='usa_state',
            name='desc',
            field=models.CharField(default='none', max_length=280),
        ),
        migrations.AddField(
            model_name='usa_state',
            name='park_qnt',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
