# Generated by Django 2.2.4 on 2020-05-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=150)),
                ('park_id', models.CharField(max_length=30)),
                ('park_tag', models.CharField(max_length=20)),
                ('overall', models.CharField(max_length=20)),
                ('service', models.CharField(max_length=20)),
                ('behaviour', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=500)),
                ('img', models.FileField(default='none', upload_to='review')),
            ],
        ),
    ]
