# Generated by Django 2.2.4 on 2020-05-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='p_date',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user_nm',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
