# Generated by Django 2.2.4 on 2020-06-01 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200530_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='img',
        ),
        migrations.CreateModel(
            name='Imd_Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='review', verbose_name='Image')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Review')),
            ],
        ),
    ]
