# Generated by Django 2.2.4 on 2020-06-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200601_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imd_review',
            name='rid',
            field=models.CharField(max_length=150),
        ),
    ]
