# Generated by Django 2.2.4 on 2020-06-05 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200601_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nm', models.CharField(max_length=100)),
                ('em', models.CharField(max_length=100)),
                ('feed', models.CharField(max_length=2000)),
                ('p_date', models.CharField(max_length=20)),
            ],
        ),
    ]
