# Generated by Django 2.2.4 on 2020-06-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=10)),
                ('u_id', models.CharField(max_length=100)),
            ],
        ),
    ]
