# Generated by Django 2.2.4 on 2020-06-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='p_id',
            field=models.IntegerField(max_length=100),
        ),
    ]
