# Generated by Django 2.2.4 on 2020-06-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200609_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('tag', models.CharField(max_length=10)),
                ('dt', models.CharField(max_length=100)),
                ('qnt', models.IntegerField()),
            ],
        ),
    ]
