# Generated by Django 2.2.4 on 2020-06-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_trending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trending',
            name='p_id',
            field=models.CharField(max_length=100),
        ),
    ]
