# Generated by Django 2.2.4 on 2020-08-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20200616_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_id', models.IntegerField()),
                ('img', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=1000)),
                ('dt', models.CharField(max_length=50)),
                ('rcount', models.CharField(max_length=50)),
                ('lnk', models.CharField(max_length=250)),
            ],
        ),
    ]
