# Generated by Django 2.2.4 on 2020-09-01 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_twitter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitter',
            name='des',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='img',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='lnk',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='twitter',
            name='rcount',
        ),
        migrations.AddField(
            model_name='twitter',
            name='twit_json',
            field=models.CharField(default='Null', max_length=10000),
            preserve_default=False,
        ),
    ]
