# Generated by Django 2.2.4 on 2020-09-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_auto_20200912_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='park_hotel',
            name='park_json',
        ),
        migrations.AddField(
            model_name='park_hotel',
            name='h_img',
            field=models.CharField(default='none', max_length=500),
        ),
        migrations.AddField(
            model_name='park_hotel',
            name='h_name',
            field=models.CharField(default='none', max_length=1000),
        ),
    ]
