# Generated by Django 2.2.4 on 2020-09-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_auto_20200913_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='park_hotel',
            name='km',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
