# Generated by Django 2.2.4 on 2020-09-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_park_hotel_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park_hotel',
            name='km',
            field=models.FloatField(),
        ),
    ]
