# Generated by Django 2.2.4 on 2020-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20200916_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='park_hotel',
            name='cat',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
